export const totalCountries = document.querySelector('.total-countries')
export const countriesCount = document.querySelector('.countries-count')
export const startingWordBtn = document.querySelector('.starting-word.btn')
export const anyWordBtn = document.querySelector('.any-word.btn')
export const searchBar = document.querySelector('#search-bar')
export const arrowBtn = document.querySelector('.arrow-button')
export const countriesList = document.querySelector('.countries-list')
